# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-10 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectlibrary',
            unique_together=set([('project', 'library')]),
        ),
    ]
