# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-10 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170710_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlibrary',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libraries', to='api.Project'),
        ),
    ]
